/******************************************************************************
*  Generated by PSoC Designer 5.0.1127.0
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "Counter8_1.h"
#include "Counter8_2.h"
#include "LCD.h"
#include "LED_1.h"
#include "LED_2.h"
#include "LED_3.h"

#endif
