//*****************************************************************************
//*****************************************************************************
//  FILENAME: LED_0.h
//   Version: 1.2, Updated on 2009/10/9 at 10:6:29                                          
//  Generated by PSoC Designer 5.0.1127.0
//
//  DESCRIPTION: LED_0 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2009. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  LED_0_Stop
#pragma fastcall16  LED_0_Start
#pragma fastcall16  LED_0_On
#pragma fastcall16  LED_0_Off
#pragma fastcall16  LED_0_Switch
#pragma fastcall16  LED_0_Invert
#pragma fastcall16  LED_0_GetState


//-------------------------------------------------
// Constants for LED_0 API's.
//-------------------------------------------------
//
#define  LED_0_ON   1
#define  LED_0_OFF  0

//-------------------------------------------------
// Prototypes of the LED_0 API.
//-------------------------------------------------
extern void  LED_0_Start(void);                                     
extern void  LED_0_Stop(void);                                      
extern void  LED_0_On(void);                                      
extern void  LED_0_Off(void);                                      
extern void  LED_0_Switch(BYTE bSwitch);
extern void  LED_0_Invert(void);                                         
extern BYTE  LED_0_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------




